# Numpy Assignment - Arif Aygun

In [37]:
import numpy as np
import pandas as pd

### 1- Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [38]:

sizes = [140, 110, 2250, 160, 120, 220, 180, 1900, 80, 100] # List of house sizes in square meters

rooms = [5, 2, 4, 7, 5, 5, 3, 4, 4, 6] # List of number of rooms in the house

prices = [225000, 132000, 213000, 200000, 95000, 77000, 190000, 280000, 390000, 320000] # List of house prices in dollars

In [39]:
house_data = np.array([sizes, rooms, prices]) # combining three list into a single array
house_data

array([[   140,    110,   2250,    160,    120,    220,    180,   1900,
            80,    100],
       [     5,      2,      4,      7,      5,      5,      3,      4,
             4,      6],
       [225000, 132000, 213000, 200000,  95000,  77000, 190000, 280000,
        390000, 320000]])

Representing of house features is not good to study and uderstand in this array form.

### 2- Transpose the array you have created, so that every line can represent features of one house.

In [40]:
house_data = house_data.T# Transposing the array

print(house_data) # Printing the transposed array; each row represents a single house

[[   140      5 225000]
 [   110      2 132000]
 [  2250      4 213000]
 [   160      7 200000]
 [   120      5  95000]
 [   220      5  77000]
 [   180      3 190000]
 [  1900      4 280000]
 [    80      4 390000]
 [   100      6 320000]]


In this transposed array, each row represents the features of a single house.

- First column representing its size in square meters.
- Second column representing the number of rooms.
- Third column representing its price in dollars.

House features are in a two dimensional array where each row represents a single house, and the columns represent the house's size, number of rooms, and price.

The form of data is better now. Using the T method to transpose the array so that the rows and columns are in the correct order.

### 3- Display the shape of the array and explain what it means.

In [41]:
print(house_data.shape)

(10, 3)


The shape of the house_data array is (10, 3).

This means that the array has 10 rows and 3 columns.
Particularly, the array contains data for 10 houses, and each house is represented by 3 features (size in square meters, number of rooms, price in thousands of dollars)

- The first number (10) represents the number of rows in the array which is also the number of houses in our data.
- The second number (3) represents the number of columns in the array, which is the number of features for each house.

Now, to knowe the shape of an array can be useful. It can help us to understand the structure of our data and to perform indexing, slicing, and reshaping.

### 4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [42]:
earthquakes=pd.read_csv(r"C:\Users\AAygun\Documents\GitHub\Data Sets\Magnimind\earthquakes1970-2014.csv")
earthquakes 

DateTime  Latitude  Longitude   Depth  Magnitude MagType  \
0     1970/01/04 17:00:40.20   24.1390   102.5030   31.00        7.5      Ms   
1     1970/01/06 05:35:51.80   -9.6280   151.4580    8.00        6.2      Ms   
2     1970/01/08 17:12:39.10  -34.7410   178.5680  179.00        6.1      Mb   
3     1970/01/10 12:07:08.60    6.8250   126.7370   73.00        6.1      Mb   
4     1970/01/16 08:05:39.00   60.2800  -152.6600   85.00        6.0      ML   
...                      ...       ...        ...     ...        ...     ...   
5299  2013/12/01 06:29:57.80    2.0440    96.8261   20.00        6.0      Mw   
5300  2013/12/08 17:24:54.20   44.4438   149.1667   28.00        6.1      Mw   
5301  2013/12/17 23:38:08.10   20.7635   146.7599   16.06        6.2      Mw   
5302  2014/01/01 16:03:28.89  -13.8779   167.2434  187.00        6.5      Mw   
5303  2014/01/13 04:01:04.69   19.0014   -66.8478   28.00        6.4      Mw   

      NbStations   Gap  Distance   RMS Source       EventID  
0           90.0   NaN       NaN  0.00    NEI  1.970010e+09  
1           85.0   NaN       NaN  0.00    NEI  1.970011e+09  
2           59.0   NaN       NaN  0.00    NEI  1.970011e+09  
3           91.0   NaN       NaN  0.00    NEI  1.970011e+09  
4            0.0   NaN       NaN   NaN     AK           NaN  
...          ...   ...       ...   ...    ...           ...  
5299         NaN  27.0       1.0  0.89     us  2.013120e+09  
5300         NaN  26.0       5.0  0.99     us  2.013121e+09  
5301         NaN  14.0       4.0  0.74     us  2.013122e+09  
5302         NaN  14.0       4.0  0.67     us  2.014010e+09  
5303         NaN  21.0       1.0  1.42     us  2.014011e+09  

[5304 rows x 12 columns]

In [43]:
earthquakes.shape

(5304, 12)

### 5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [44]:
sliced_arrays = earthquakes.loc[:20,['Longitude', 'Magnitude', 'MagType', 'NbStations', 'EventID']]
sliced_arrays

Longitude  Magnitude MagType  NbStations       EventID
0    102.5030        7.5      Ms        90.0  1.970010e+09
1    151.4580        6.2      Ms        85.0  1.970011e+09
2    178.5680        6.1      Mb        59.0  1.970011e+09
3    126.7370        6.1      Mb        91.0  1.970011e+09
4   -152.6600        6.0      ML         0.0           NaN
5   -177.3490        6.5      Mb       175.0  1.970012e+09
6    142.9660        6.4      Ms       199.0  1.970012e+09
7   -104.2980        6.6      Ms       140.0  1.970012e+09
8    166.3700        6.4      Ms        91.0  1.970013e+09
9    -99.4840        6.5      Ms       100.0  1.970020e+09
10   122.1170        6.6      Ms        94.0  1.970021e+09
11   100.7750        6.1      Ms        57.0  1.970021e+09
12   103.0310        6.0      Ms        94.0  1.970022e+09
13  -179.5898        6.0      ML         0.0           NaN
14  -175.0400        6.1      ML         0.0           NaN
15   143.7070        6.2      Ms        82.0  1.970030e+09
16   168.6030        6.5      Ms        61.0  1.970031e+09
17   148.8700        6.0      Mb        65.0  1.970031e+09
18  -153.9700        6.5      ML         0.0           NaN
19   -69.4990        6.0      Mb       118.0  1.970032e+09
20   173.7500        6.5      ML         0.0           NaN

### 6- Display the row numbers where last values are equal to 4.5 or higher.

In [45]:
sliced_arrays[sliced_arrays['EventID'] >= 4.5].index

Int64Index([0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 19], dtype='int64')

### 7- Assign 1 to first row.

In [46]:
sliced_arrays.loc[0] = 1
sliced_arrays

Longitude  Magnitude MagType  NbStations       EventID
0      1.0000        1.0       1         1.0  1.000000e+00
1    151.4580        6.2      Ms        85.0  1.970011e+09
2    178.5680        6.1      Mb        59.0  1.970011e+09
3    126.7370        6.1      Mb        91.0  1.970011e+09
4   -152.6600        6.0      ML         0.0           NaN
5   -177.3490        6.5      Mb       175.0  1.970012e+09
6    142.9660        6.4      Ms       199.0  1.970012e+09
7   -104.2980        6.6      Ms       140.0  1.970012e+09
8    166.3700        6.4      Ms        91.0  1.970013e+09
9    -99.4840        6.5      Ms       100.0  1.970020e+09
10   122.1170        6.6      Ms        94.0  1.970021e+09
11   100.7750        6.1      Ms        57.0  1.970021e+09
12   103.0310        6.0      Ms        94.0  1.970022e+09
13  -179.5898        6.0      ML         0.0           NaN
14  -175.0400        6.1      ML         0.0           NaN
15   143.7070        6.2      Ms        82.0  1.970030e+09
16   168.6030        6.5      Ms        61.0  1.970031e+09
17   148.8700        6.0      Mb        65.0  1.970031e+09
18  -153.9700        6.5      ML         0.0           NaN
19   -69.4990        6.0      Mb       118.0  1.970032e+09
20   173.7500        6.5      ML         0.0           NaN

### 8- Save the final state of the array to disk. You are going to use this in the next assignment.

In [47]:
pd.DataFrame(sliced_arrays).to_csv("new_earthquakes.csv")

### 9- Load the array you saved in the previous lesson from the disk.

In [48]:
load_array = pd.read_csv("new_earthquakes.csv")
load_array

Unnamed: 0  Longitude  Magnitude MagType  NbStations       EventID
0            0     1.0000        1.0       1         1.0  1.000000e+00
1            1   151.4580        6.2      Ms        85.0  1.970011e+09
2            2   178.5680        6.1      Mb        59.0  1.970011e+09
3            3   126.7370        6.1      Mb        91.0  1.970011e+09
4            4  -152.6600        6.0      ML         0.0           NaN
5            5  -177.3490        6.5      Mb       175.0  1.970012e+09
6            6   142.9660        6.4      Ms       199.0  1.970012e+09
7            7  -104.2980        6.6      Ms       140.0  1.970012e+09
8            8   166.3700        6.4      Ms        91.0  1.970013e+09
9            9   -99.4840        6.5      Ms       100.0  1.970020e+09
10          10   122.1170        6.6      Ms        94.0  1.970021e+09
11          11   100.7750        6.1      Ms        57.0  1.970021e+09
12          12   103.0310        6.0      Ms        94.0  1.970022e+09
13          13  -179.5898        6.0      ML         0.0           NaN
14          14  -175.0400        6.1      ML         0.0           NaN
15          15   143.7070        6.2      Ms        82.0  1.970030e+09
16          16   168.6030        6.5      Ms        61.0  1.970031e+09
17          17   148.8700        6.0      Mb        65.0  1.970031e+09
18          18  -153.9700        6.5      ML         0.0           NaN
19          19   -69.4990        6.0      Mb       118.0  1.970032e+09
20          20   173.7500        6.5      ML         0.0           NaN

### 10- Display the mean and the standard deviation for each column.

In [49]:
load_array.std()

C:\Users\AAygun\AppData\Local\Temp\ipykernel_8568\2177897315.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  load_array.std()


Unnamed: 0    6.204837e+00
Longitude     1.423041e+02
Magnitude     1.170592e+00
NbStations    5.820052e+01
EventID       4.925048e+08
dtype: float64

### 11- Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)

In [50]:
load_array['Longitude'] -= 1
load_array['Magnitude'] -= 25
load_array['NbStations'] -= 25
load_array['NbStations'] -= 10
load_array['EventID'] -= 4
load_array

Unnamed: 0  Longitude  Magnitude MagType  NbStations       EventID
0            0     0.0000      -24.0       1       -34.0 -3.000000e+00
1            1   150.4580      -18.8      Ms        50.0  1.970011e+09
2            2   177.5680      -18.9      Mb        24.0  1.970011e+09
3            3   125.7370      -18.9      Mb        56.0  1.970011e+09
4            4  -153.6600      -19.0      ML       -35.0           NaN
5            5  -178.3490      -18.5      Mb       140.0  1.970012e+09
6            6   141.9660      -18.6      Ms       164.0  1.970012e+09
7            7  -105.2980      -18.4      Ms       105.0  1.970012e+09
8            8   165.3700      -18.6      Ms        56.0  1.970013e+09
9            9  -100.4840      -18.5      Ms        65.0  1.970020e+09
10          10   121.1170      -18.4      Ms        59.0  1.970021e+09
11          11    99.7750      -18.9      Ms        22.0  1.970021e+09
12          12   102.0310      -19.0      Ms        59.0  1.970022e+09
13          13  -180.5898      -19.0      ML       -35.0           NaN
14          14  -176.0400      -18.9      ML       -35.0           NaN
15          15   142.7070      -18.8      Ms        47.0  1.970030e+09
16          16   167.6030      -18.5      Ms        26.0  1.970031e+09
17          17   147.8700      -19.0      Mb        30.0  1.970031e+09
18          18  -154.9700      -18.5      ML       -35.0           NaN
19          19   -70.4990      -19.0      Mb        83.0  1.970032e+09
20          20   172.7500      -18.5      ML       -35.0           NaN

### 12- Multiply each element by 2. (Remember it can be done in one line of code.)

In [51]:
multiplied_array = load_array * 2
multiplied_array

Unnamed: 0  Longitude  Magnitude MagType  NbStations       EventID
0            0     0.0000      -48.0      11       -68.0 -6.000000e+00
1            2   300.9160      -37.6    MsMs       100.0  3.940021e+09
2            4   355.1360      -37.8    MbMb        48.0  3.940022e+09
3            6   251.4740      -37.8    MbMb       112.0  3.940022e+09
4            8  -307.3200      -38.0    MLML       -70.0           NaN
5           10  -356.6980      -37.0    MbMb       280.0  3.940024e+09
6           12   283.9320      -37.2    MsMs       328.0  3.940024e+09
7           14  -210.5960      -36.8    MsMs       210.0  3.940024e+09
8           16   330.7400      -37.2    MsMs       112.0  3.940025e+09
9           18  -200.9680      -37.0    MsMs       130.0  3.940041e+09
10          20   242.2340      -36.8    MsMs       118.0  3.940041e+09
11          22   199.5500      -37.8    MsMs        44.0  3.940041e+09
12          24   204.0620      -38.0    MsMs       118.0  3.940045e+09
13          26  -361.1796      -38.0    MLML       -70.0           NaN
14          28  -352.0800      -37.8    MLML       -70.0           NaN
15          30   285.4140      -37.6    MsMs        94.0  3.940061e+09
16          32   335.2060      -37.0    MsMs        52.0  3.940062e+09
17          34   295.7400      -38.0    MbMb        60.0  3.940062e+09
18          36  -309.9400      -37.0    MLML       -70.0           NaN
19          38  -140.9980      -38.0    MbMb       166.0  3.940063e+09
20          40   345.5000      -37.0    MLML       -70.0           NaN