<a href="https://colab.research.google.com/github/ArifAygun/Magnimind-Jan2023-Assignments/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Assignment - Arif Aygun

In [1]:
import numpy as np
import pandas as pd

### 1- Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [2]:

sizes = [140, 110, 2250, 160, 120, 220, 180, 1900, 80, 100] # List of house sizes in square meters

rooms = [5, 2, 4, 7, 5, 5, 3, 4, 4, 6] # List of number of rooms in the house

prices = [225000, 132000, 213000, 200000, 95000, 77000, 190000, 280000, 390000, 320000] # List of house prices in dollars

In [3]:
house_data = np.array([sizes, rooms, prices]) # combining three list into a single array
house_data

array([[   140,    110,   2250,    160,    120,    220,    180,   1900,
            80,    100],
       [     5,      2,      4,      7,      5,      5,      3,      4,
             4,      6],
       [225000, 132000, 213000, 200000,  95000,  77000, 190000, 280000,
        390000, 320000]])

Representing of house features is not good to study and uderstand in this array form.

### 2- Transpose the array you have created, so that every line can represent features of one house.

In [4]:
house_data = house_data.T# Transposing the array

print(house_data) # Printing the transposed array; each row represents a single house

[[   140      5 225000]
 [   110      2 132000]
 [  2250      4 213000]
 [   160      7 200000]
 [   120      5  95000]
 [   220      5  77000]
 [   180      3 190000]
 [  1900      4 280000]
 [    80      4 390000]
 [   100      6 320000]]


In this transposed array, each row represents the features of a single house.

- First column representing its size in square meters.
- Second column representing the number of rooms.
- Third column representing its price in dollars.

House features are in a two dimensional array where each row represents a single house, and the columns represent the house's size, number of rooms, and price.

The form of data is better now. Using the T method to transpose the array so that the rows and columns are in the correct order.

### 3- Display the shape of the array and explain what it means.

In [5]:
print(house_data.shape)

(10, 3)


The shape of the house_data array is (10, 3).

This means that the array has 10 rows and 3 columns.
Particularly, the array contains data for 10 houses, and each house is represented by 3 features (size in square meters, number of rooms, price in thousands of dollars)

- The first number (10) represents the number of rows in the array which is also the number of houses in our data.
- The second number (3) represents the number of columns in the array, which is the number of features for each house.

Now, to knowe the shape of an array can be useful. It can help us to understand the structure of our data and to perform indexing, slicing, and reshaping.

### 4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [15]:
#earthquakes=pd.read_csv(r"C:\Users\AAygun\Documents\GitHub\Data Sets\Magnimind\earthquakes1970-2014.csv")
#earthquakes 

import pandas as pd
import numpy as np
earthquakes = pd.read_csv(Path)
earthquakes.head()

DateTime  Latitude  Longitude  Depth  Magnitude MagType  \
0  1970/01/04 17:00:40.20    24.139    102.503   31.0        7.5      Ms   
1  1970/01/06 05:35:51.80    -9.628    151.458    8.0        6.2      Ms   
2  1970/01/08 17:12:39.10   -34.741    178.568  179.0        6.1      Mb   
3  1970/01/10 12:07:08.60     6.825    126.737   73.0        6.1      Mb   
4  1970/01/16 08:05:39.00    60.280   -152.660   85.0        6.0      ML   

   NbStations  Gap  Distance  RMS Source       EventID  
0        90.0  NaN       NaN  0.0    NEI  1.970010e+09  
1        85.0  NaN       NaN  0.0    NEI  1.970011e+09  
2        59.0  NaN       NaN  0.0    NEI  1.970011e+09  
3        91.0  NaN       NaN  0.0    NEI  1.970011e+09  
4         0.0  NaN       NaN  NaN     AK           NaN

In [16]:
earthquakes.shape

(5304, 12)

### 5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [17]:
sliced_arrays = earthquakes.loc[:20,['Longitude', 'Magnitude', 'MagType', 'NbStations', 'EventID']]
sliced_arrays

Longitude  Magnitude MagType  NbStations       EventID
0    102.5030        7.5      Ms        90.0  1.970010e+09
1    151.4580        6.2      Ms        85.0  1.970011e+09
2    178.5680        6.1      Mb        59.0  1.970011e+09
3    126.7370        6.1      Mb        91.0  1.970011e+09
4   -152.6600        6.0      ML         0.0           NaN
5   -177.3490        6.5      Mb       175.0  1.970012e+09
6    142.9660        6.4      Ms       199.0  1.970012e+09
7   -104.2980        6.6      Ms       140.0  1.970012e+09
8    166.3700        6.4      Ms        91.0  1.970013e+09
9    -99.4840        6.5      Ms       100.0  1.970020e+09
10   122.1170        6.6      Ms        94.0  1.970021e+09
11   100.7750        6.1      Ms        57.0  1.970021e+09
12   103.0310        6.0      Ms        94.0  1.970022e+09
13  -179.5898        6.0      ML         0.0           NaN
14  -175.0400        6.1      ML         0.0           NaN
15   143.7070        6.2      Ms        82.0  1.970030e+09
16   168.6030        6.5      Ms        61.0  1.970031e+09
17   148.8700        6.0      Mb        65.0  1.970031e+09
18  -153.9700        6.5      ML         0.0           NaN
19   -69.4990        6.0      Mb       118.0  1.970032e+09
20   173.7500        6.5      ML         0.0           NaN

### 6- Display the row numbers where last values are equal to 4.5 or higher.

In [18]:
sliced_arrays[sliced_arrays['EventID'] >= 4.5].index

Int64Index([0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 19], dtype='int64')

### 7- Assign 1 to first row.

In [19]:
sliced_arrays.loc[0] = 1
sliced_arrays

Longitude  Magnitude MagType  NbStations       EventID
0      1.0000        1.0       1         1.0  1.000000e+00
1    151.4580        6.2      Ms        85.0  1.970011e+09
2    178.5680        6.1      Mb        59.0  1.970011e+09
3    126.7370        6.1      Mb        91.0  1.970011e+09
4   -152.6600        6.0      ML         0.0           NaN
5   -177.3490        6.5      Mb       175.0  1.970012e+09
6    142.9660        6.4      Ms       199.0  1.970012e+09
7   -104.2980        6.6      Ms       140.0  1.970012e+09
8    166.3700        6.4      Ms        91.0  1.970013e+09
9    -99.4840        6.5      Ms       100.0  1.970020e+09
10   122.1170        6.6      Ms        94.0  1.970021e+09
11   100.7750        6.1      Ms        57.0  1.970021e+09
12   103.0310        6.0      Ms        94.0  1.970022e+09
13  -179.5898        6.0      ML         0.0           NaN
14  -175.0400        6.1      ML         0.0           NaN
15   143.7070        6.2      Ms        82.0  1.970030e+09
16   168.6030        6.5      Ms        61.0  1.970031e+09
17   148.8700        6.0      Mb        65.0  1.970031e+09
18  -153.9700        6.5      ML         0.0           NaN
19   -69.4990        6.0      Mb       118.0  1.970032e+09
20   173.7500        6.5      ML         0.0           NaN

### 8- Save the final state of the array to disk. You are going to use this in the next assignment.

In [20]:
pd.DataFrame(sliced_arrays).to_csv("new_earthquakes.csv")

### 9- Load the array you saved in the previous lesson from the disk.

In [21]:
load_array = pd.read_csv("new_earthquakes.csv")
load_array

Unnamed: 0  Longitude  Magnitude MagType  NbStations       EventID
0            0     1.0000        1.0       1         1.0  1.000000e+00
1            1   151.4580        6.2      Ms        85.0  1.970011e+09
2            2   178.5680        6.1      Mb        59.0  1.970011e+09
3            3   126.7370        6.1      Mb        91.0  1.970011e+09
4            4  -152.6600        6.0      ML         0.0           NaN
5            5  -177.3490        6.5      Mb       175.0  1.970012e+09
6            6   142.9660        6.4      Ms       199.0  1.970012e+09
7            7  -104.2980        6.6      Ms       140.0  1.970012e+09
8            8   166.3700        6.4      Ms        91.0  1.970013e+09
9            9   -99.4840        6.5      Ms       100.0  1.970020e+09
10          10   122.1170        6.6      Ms        94.0  1.970021e+09
11          11   100.7750        6.1      Ms        57.0  1.970021e+09
12          12   103.0310        6.0      Ms        94.0  1.970022e+09
13          13  -179.5898        6.0      ML         0.0           NaN
14          14  -175.0400        6.1      ML         0.0           NaN
15          15   143.7070        6.2      Ms        82.0  1.970030e+09
16          16   168.6030        6.5      Ms        61.0  1.970031e+09
17          17   148.8700        6.0      Mb        65.0  1.970031e+09
18          18  -153.9700        6.5      ML         0.0           NaN
19          19   -69.4990        6.0      Mb       118.0  1.970032e+09
20          20   173.7500        6.5      ML         0.0           NaN

### 10- Display the mean and the standard deviation for each column.

In [22]:
load_array.std()

<ipython-input-22-42e12db9ed24>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  load_array.std()


Unnamed: 0    6.204837e+00
Longitude     1.423041e+02
Magnitude     1.170592e+00
NbStations    5.820052e+01
EventID       4.925048e+08
dtype: float64

### 11- Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)

In [23]:
load_array['Longitude'] -= 1
load_array['Magnitude'] -= 25
load_array['NbStations'] -= 25
load_array['NbStations'] -= 10
load_array['EventID'] -= 4
load_array

Unnamed: 0  Longitude  Magnitude MagType  NbStations       EventID
0            0     0.0000      -24.0       1       -34.0 -3.000000e+00
1            1   150.4580      -18.8      Ms        50.0  1.970011e+09
2            2   177.5680      -18.9      Mb        24.0  1.970011e+09
3            3   125.7370      -18.9      Mb        56.0  1.970011e+09
4            4  -153.6600      -19.0      ML       -35.0           NaN
5            5  -178.3490      -18.5      Mb       140.0  1.970012e+09
6            6   141.9660      -18.6      Ms       164.0  1.970012e+09
7            7  -105.2980      -18.4      Ms       105.0  1.970012e+09
8            8   165.3700      -18.6      Ms        56.0  1.970013e+09
9            9  -100.4840      -18.5      Ms        65.0  1.970020e+09
10          10   121.1170      -18.4      Ms        59.0  1.970021e+09
11          11    99.7750      -18.9      Ms        22.0  1.970021e+09
12          12   102.0310      -19.0      Ms        59.0  1.970022e+09
13          13  -180.5898      -19.0      ML       -35.0           NaN
14          14  -176.0400      -18.9      ML       -35.0           NaN
15          15   142.7070      -18.8      Ms        47.0  1.970030e+09
16          16   167.6030      -18.5      Ms        26.0  1.970031e+09
17          17   147.8700      -19.0      Mb        30.0  1.970031e+09
18          18  -154.9700      -18.5      ML       -35.0           NaN
19          19   -70.4990      -19.0      Mb        83.0  1.970032e+09
20          20   172.7500      -18.5      ML       -35.0           NaN

### 12- Multiply each element by 2. (Remember it can be done in one line of code.)

In [24]:
multiplied_array = load_array * 2
multiplied_array

Unnamed: 0  Longitude  Magnitude MagType  NbStations       EventID
0            0     0.0000      -48.0      11       -68.0 -6.000000e+00
1            2   300.9160      -37.6    MsMs       100.0  3.940021e+09
2            4   355.1360      -37.8    MbMb        48.0  3.940022e+09
3            6   251.4740      -37.8    MbMb       112.0  3.940022e+09
4            8  -307.3200      -38.0    MLML       -70.0           NaN
5           10  -356.6980      -37.0    MbMb       280.0  3.940024e+09
6           12   283.9320      -37.2    MsMs       328.0  3.940024e+09
7           14  -210.5960      -36.8    MsMs       210.0  3.940024e+09
8           16   330.7400      -37.2    MsMs       112.0  3.940025e+09
9           18  -200.9680      -37.0    MsMs       130.0  3.940041e+09
10          20   242.2340      -36.8    MsMs       118.0  3.940041e+09
11          22   199.5500      -37.8    MsMs        44.0  3.940041e+09
12          24   204.0620      -38.0    MsMs       118.0  3.940045e+09
13          26  -361.1796      -38.0    MLML       -70.0           NaN
14          28  -352.0800      -37.8    MLML       -70.0           NaN
15          30   285.4140      -37.6    MsMs        94.0  3.940061e+09
16          32   335.2060      -37.0    MsMs        52.0  3.940062e+09
17          34   295.7400      -38.0    MbMb        60.0  3.940062e+09
18          36  -309.9400      -37.0    MLML       -70.0           NaN
19          38  -140.9980      -38.0    MbMb       166.0  3.940063e+09
20          40   345.5000      -37.0    MLML       -70.0           NaN

# **OFFICE HOUR SOLUTIONS**

Solution:1

In [ ]:
import numpy as np

In [ ]:
#Creating 10 houses with random size of minimum 100 m-squared to 500 m-squared
House_size = np.random.randint(100,500,10,dtype=int) #randint support integers only
House_size = sorted(House_size, reverse=True)

#Creating the number of rooms randomly, minimum 1 room to maximum 2 rooms.
House_rooms = np.random.choice(range(1,3), size=10, replace=True)
House_rooms = sorted(House_rooms, reverse=True)

#Creating the price randomly between $300_000 to $1_000_000
House_price = np.random.choice(range(300_000, 1_000_000), size=10,replace=True)
House_price = sorted(House_price, reverse=True)

#Combining the above arrays into a single array
House_features = np.array([House_size, House_rooms, House_price])
House_features 

In [ ]:
House_features.shape

Solution:2

In [ ]:
House_features = House_features.transpose()

In [ ]:
House_features.shape

Solution:3

In [ ]:
print("""
The House_features array has {rows} rows that represents number of houses,\nand {columns} columns which represents number of features for each house""". format(rows= House_features.shape[0], columns= House_features.shape[1]))

Solution:3

In [8]:
#from google.colab import drive
#drive.mounth('content/drive')

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
import os
for Dir, Folders, Files in os.walk(os.getcwd()):
  for File in Files:
    if File == 'earthquakes1970-2014.csv':
      Path = os.path.join(Dir, File)
      print(Path)

/content/drive/Othercomputers/My MacBook Pro/GitHub/Data Sets/Magnimind/earthquakes1970-2014.csv
/content/drive/Othercomputers/My MacBook Pro/GitHub/Magnimind Eski Projeler/Romuald Francis Yang repos/Magnimind DS/datasets/earthquakes1970-2014.csv
/content/drive/MyDrive/Colab Datasets/earthquakes1970-2014.csv


Path is a data address path

In [10]:
import pandas as pd
import numpy as np
df = pd.read_csv(Path)
df.head()

DateTime  Latitude  Longitude  Depth  Magnitude MagType  \
0  1970/01/04 17:00:40.20    24.139    102.503   31.0        7.5      Ms   
1  1970/01/06 05:35:51.80    -9.628    151.458    8.0        6.2      Ms   
2  1970/01/08 17:12:39.10   -34.741    178.568  179.0        6.1      Mb   
3  1970/01/10 12:07:08.60     6.825    126.737   73.0        6.1      Mb   
4  1970/01/16 08:05:39.00    60.280   -152.660   85.0        6.0      ML   

   NbStations  Gap  Distance  RMS Source       EventID  
0        90.0  NaN       NaN  0.0    NEI  1.970010e+09  
1        85.0  NaN       NaN  0.0    NEI  1.970011e+09  
2        59.0  NaN       NaN  0.0    NEI  1.970011e+09  
3        91.0  NaN       NaN  0.0    NEI  1.970011e+09  
4         0.0  NaN       NaN  NaN     AK           NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5304 entries, 0 to 5303
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   DateTime    5304 non-null   object 
 1   Latitude    5304 non-null   float64
 2   Longitude   5304 non-null   float64
 3   Depth       5304 non-null   float64
 4   Magnitude   5304 non-null   float64
 5   MagType     5304 non-null   object 
 6   NbStations  5250 non-null   float64
 7   Gap         172 non-null    float64
 8   Distance    170 non-null    float64
 9   RMS         5264 non-null   float64
 10  Source      5304 non-null   object 
 11  EventID     5242 non-null   float64
dtypes: float64(9), object(3)
memory usage: 497.4+ KB


In [12]:
from pandas.core.arrays.sparse import dtype
#Converting dataframe to an array
np.array(df)

#Converting dataframe to an array
df_array = df.to_numpy()

#shape of the array
df_array.shape

#slicing
df_array_sliced = df_array[:20, [2,4,5,6,11]]
np.where(df_array_sliced[:,1]>=6.5)
np.where(df_array_sliced[:,1]>=4.5)

#replacing values
#replacing a single value at the given row and column
df_array_sliced[0,1]=1

#replacing values of the whole row
df_array_sliced[0]=1
df_array_sliced[0] == df_array_sliced[0,:]
#display the array
display(df_array_sliced)
display(pd.DataFrame(df_array_sliced))

df_array_sliced_numeric = np.asarray(np.delete(df_array_sliced, 2, axis=1), dtype=float)

#the following code will remove with null value
df_array_sliced_numeric[~np.isnan(df_array_sliced_numeric).any(axis=1)].mean(axis=1)

df_array_sliced_numeric[~np.isnan(df_array_sliced_numeric).any(axis=1)] - [1,25,10,4]
df_array_sliced_numeric[~np.isnan(df_array_sliced_numeric).any(axis=1)]*4



array([[1, 1, 1, 1, 1],
       [151.458, 6.2, 'Ms', 85.0, 1970010640.0],
       [178.568, 6.1, 'Mb', 59.0, 1970010840.0],
       [126.736999999999, 6.1, 'Mb', 91.0, 1970011040.0],
       [-152.66, 6.0, 'ML', 0.0, nan],
       [-177.348999999999, 6.5, 'Mb', 175.0, 1970012040.0],
       [142.966, 6.4, 'Ms', 199.0, 1970012040.0],
       [-104.298, 6.6, 'Ms', 140.0, 1970012140.0],
       [166.37, 6.4, 'Ms', 91.0, 1970012640.0],
       [-99.48399999999991, 6.5, 'Ms', 100.0, 1970020440.0],
       [122.117, 6.6, 'Ms', 94.0, 1970020540.0],
       [100.775, 6.1, 'Ms', 57.0, 1970020640.0],
       [103.031, 6.0, 'Ms', 94.0, 1970022440.0],
       [-179.5898, 6.0, 'ML', 0.0, nan],
       [-175.039999999999, 6.1, 'ML', 0.0, nan],
       [143.706999999999, 6.2, 'Ms', 82.0, 1970030440.0],
       [168.603, 6.5, 'Ms', 61.0, 1970030940.0],
       [148.87, 6.0, 'Mb', 65.0, 1970031040.0],
       [-153.97, 6.5, 'ML', 0.0, nan],
       [-69.49899999999991, 6.0, 'Mb', 118.0, 1970031540.0]], dtype=object)

0    1   2      3             4
0          1    1   1      1             1
1    151.458  6.2  Ms   85.0  1970010640.0
2    178.568  6.1  Mb   59.0  1970010840.0
3    126.737  6.1  Mb   91.0  1970011040.0
4    -152.66  6.0  ML    0.0           NaN
5   -177.349  6.5  Mb  175.0  1970012040.0
6    142.966  6.4  Ms  199.0  1970012040.0
7   -104.298  6.6  Ms  140.0  1970012140.0
8     166.37  6.4  Ms   91.0  1970012640.0
9    -99.484  6.5  Ms  100.0  1970020440.0
10   122.117  6.6  Ms   94.0  1970020540.0
11   100.775  6.1  Ms   57.0  1970020640.0
12   103.031  6.0  Ms   94.0  1970022440.0
13 -179.5898  6.0  ML    0.0           NaN
14   -175.04  6.1  ML    0.0           NaN
15   143.707  6.2  Ms   82.0  1970030440.0
16   168.603  6.5  Ms   61.0  1970030940.0
17    148.87  6.0  Mb   65.0  1970031040.0
18   -153.97  6.5  ML    0.0           NaN
19   -69.499  6.0  Mb  118.0  1970031540.0

array([[ 4.00000000e+00,  4.00000000e+00,  4.00000000e+00,
         4.00000000e+00],
       [ 6.05832000e+02,  2.48000000e+01,  3.40000000e+02,
         7.88004256e+09],
       [ 7.14272000e+02,  2.44000000e+01,  2.36000000e+02,
         7.88004336e+09],
       [ 5.06948000e+02,  2.44000000e+01,  3.64000000e+02,
         7.88004416e+09],
       [-7.09396000e+02,  2.60000000e+01,  7.00000000e+02,
         7.88004816e+09],
       [ 5.71864000e+02,  2.56000000e+01,  7.96000000e+02,
         7.88004816e+09],
       [-4.17192000e+02,  2.64000000e+01,  5.60000000e+02,
         7.88004856e+09],
       [ 6.65480000e+02,  2.56000000e+01,  3.64000000e+02,
         7.88005056e+09],
       [-3.97936000e+02,  2.60000000e+01,  4.00000000e+02,
         7.88008176e+09],
       [ 4.88468000e+02,  2.64000000e+01,  3.76000000e+02,
         7.88008216e+09],
       [ 4.03100000e+02,  2.44000000e+01,  2.28000000e+02,
         7.88008256e+09],
       [ 4.12124000e+02,  2.40000000e+01,  3.76000000e+02,
      

In [ ]:
df_array_sliced[:,3][~np.isnan(np.asarray(df_array_sliced[:,3],dtype=float))].std()

55.81343924181702

In [ ]:
#Converting dataframe to array
np.array(df)

array([['1970/01/04 17:00:40.20', 24.1389999999999, 102.503, ..., 0.0,
        'NEI', 1970010440.0],
       ['1970/01/06 05:35:51.80', -9.628, 151.458, ..., 0.0, 'NEI',
        1970010640.0],
       ['1970/01/08 17:12:39.10', -34.741, 178.568, ..., 0.0, 'NEI',
        1970010840.0],
       ...,
       ['2013/12/17 23:38:08.10', 20.7635, 146.759899999999, ..., 0.74,
        'us', 2013121720.0],
       ['2014/01/01 16:03:28.89', -13.8779, 167.2434, ..., 0.67, 'us',
        2014010120.0],
       ['2014/01/13 04:01:04.69', 19.0014, -66.8478, ..., 1.42, 'us',
        2014011320.0]], dtype=object)

In [ ]:
#converting dataframe to array
df_array = df.to_numpy()

In [ ]:
df_array.shape

(5304, 12)

In [ ]:
#slicing
df_array_sliced = df_array[:20, [2,4,5,6,11]]

In [ ]:
#filtering
df_array_sliced[df_array_sliced[:,1]>=7]

array([[102.503, 7.5, 'Ms', 90.0, 1970010440.0]], dtype=object)

In [ ]:
np.where(df_array_sliced[:,1]>=6.5)

(array([ 0,  5,  7,  9, 10, 16, 18]),)

In [ ]:
np.where(df_array_sliced[:,1]>=4.5)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),)

In [ ]:
#Replacing values
#replacing a single valueat the given row and column
df_array_sliced[0,1]=1
# replacing values of the whole row
df_array_sliced[0]=1

In [ ]:
df_array_sliced[0:2,1:]=1

In [ ]:
df_array_sliced[0] == df_array_sliced[0,:]

array([ True,  True,  True,  True,  True])

Note that in Pandas mean, for each individual column all not null values include in the mean.

But in the Numpy method when there is a null value in a column the whole row is remowed so it changes the mean of other columns with no not null value

In [ ]:
df_new.mean(numeric_only=True)

Longitude     2.211561e+01
NbStations    7.560000e+01
EventID       1.846893e+09
Magnitude     5.990000e+00
dtype: float64

Answering the questions using Dataframe

In [ ]:
#Let's check the number of rows and columns
df.shape

(5304, 12)

In [ ]:
# Slice 20 rows and column numbers 3,5,6,7,12. 
# Then, assign the array you sliced to a variable

df2 = df.iloc[:20,[2,4,5,6,11]] #separate the rows and columns to be sliced comma

display(df.head(3))

DateTime  Latitude  Longitude  Depth  Magnitude MagType  \
0  1970/01/04 17:00:40.20    24.139    102.503   31.0        7.5      Ms   
1  1970/01/06 05:35:51.80    -9.628    151.458    8.0        6.2      Ms   
2  1970/01/08 17:12:39.10   -34.741    178.568  179.0        6.1      Mb   

   NbStations  Gap  Distance  RMS Source       EventID  
0        90.0  NaN       NaN  0.0    NEI  1.970010e+09  
1        85.0  NaN       NaN  0.0    NEI  1.970011e+09  
2        59.0  NaN       NaN  0.0    NEI  1.970011e+09

In [ ]:
print(df2.shape)

(20, 5)


In [ ]:
df2.columns

Index(['Longitude', 'Magnitude', 'MagType', 'NbStations', 'EventID'], dtype='object')

In [ ]:
# First let's reorder the columns (optional)
df2 = df2[['Longitude', 'NbStations', 'EventID', 'Magnitude']]
df2.head()

Longitude  NbStations       EventID  Magnitude
0    102.503        90.0  1.970010e+09        7.5
1    151.458        85.0  1.970011e+09        6.2
2    178.568        59.0  1.970011e+09        6.1
3    126.737        91.0  1.970011e+09        6.1
4   -152.660         0.0           NaN        6.0

In [ ]:
#Display the row numbers where last values are equal to 4.5 or higher
#Since 4.5 fits with magnitude value
df2[df2.Magnitude>=4.5].index

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype='int64')

In [ ]:
# Magnitude of all rows in the original dataframe is greater than 4.5
len(df[df.Magnitude>=4.5].index) - len(df)

0

In [ ]:
#Assign 1 to first row
#method1
df2[df2.index==0] = 1
df2.loc[0:1]

Longitude  NbStations       EventID  Magnitude
0      1.000         1.0  1.000000e+00        1.0
1    151.458        85.0  1.970011e+09        6.2

In [ ]:
#Method2
df2['Magnitude'][0] = 1

In [ ]:
df2.loc[0] == df2.iloc[0]

Longitude     True
NbStations    True
EventID       True
Magnitude     True
Name: 0, dtype: bool

In [ ]:
df2.iloc[0] == df2.iloc[0,:]

Longitude     True
NbStations    True
EventID       True
Magnitude     True
Name: 0, dtype: bool

In [ ]:
df2.head(5)

Longitude  NbStations       EventID  Magnitude
0      1.000         1.0  1.000000e+00        1.0
1    151.458        85.0  1.970011e+09        6.2
2    178.568        59.0  1.970011e+09        6.1
3    126.737        91.0  1.970011e+09        6.1
4   -152.660         0.0           NaN        6.0

In [ ]:
df2.at[0,'Magnitude'] = 9
df2.at[0, ['Magnitude', 'MagType']] = (1, 'Ms')
df2.loc[0:1]

Longitude  NbStations       EventID  Magnitude MagType
0      1.000         1.0  1.000000e+00        1.0      Ms
1    151.458        85.0  1.970011e+09        6.2     NaN

In [ ]:
# Saving the final state of array to disk. 
df2.to_csv(os.path.join(os.path.dirname(Path), 'sliced_earthquakes_data.csv'), index=False)

In [ ]:
#Load the array you saved in the provious lesson from disk
df_new = pd.read_csv(os.path.join(os.path.dirname(Path), 'sliced_earthquakes_data.csv'))
df_new.head(10)


Longitude  NbStations       EventID  Magnitude MagType
0      1.000         1.0  1.000000e+00        1.0      Ms
1    151.458        85.0  1.970011e+09        6.2     NaN
2    178.568        59.0  1.970011e+09        6.1     NaN
3    126.737        91.0  1.970011e+09        6.1     NaN
4   -152.660         0.0           NaN        6.0     NaN
5   -177.349       175.0  1.970012e+09        6.5     NaN
6    142.966       199.0  1.970012e+09        6.4     NaN
7   -104.298       140.0  1.970012e+09        6.6     NaN
8    166.370        91.0  1.970013e+09        6.4     NaN
9    -99.484       100.0  1.970020e+09        6.5     NaN

In [ ]:
df_new.mean(numeric_only=True)

Longitude     2.211561e+01
NbStations    7.560000e+01
EventID       1.846893e+09
Magnitude     5.990000e+00
dtype: float64

In [ ]:
df_new.describe()

Longitude  NbStations       EventID  Magnitude
count   20.000000    20.00000  1.600000e+01  20.000000
mean    22.115610    75.60000  1.846893e+09   5.990000
std    141.999134    57.26338  4.925048e+08   1.195562
min   -179.589800     0.00000  1.000000e+00   1.000000
25%   -116.388500    43.00000  1.970012e+09   6.000000
50%    101.903000    83.50000  1.970017e+09   6.150000
75%    144.997750    95.50000  1.970024e+09   6.500000
max    178.568000   199.00000  1.970032e+09   6.600000

In [ ]:
#Display the mean and std for each column
df_new.mean(skipna=True, numeric_only=True) #skipna is True by default

Longitude     2.211561e+01
NbStations    7.560000e+01
EventID       1.846893e+09
Magnitude     5.990000e+00
dtype: float64

In [ ]:
df_new.std(numeric_only=True, skipna=True)

Longitude     1.419991e+02
NbStations    5.726338e+01
EventID       4.925048e+08
Magnitude     1.195562e+00
dtype: float64

In [ ]:
df_new.dtypes

Longitude     float64
NbStations    float64
EventID       float64
Magnitude     float64
MagType        object
dtype: object

In [ ]:
df_new.columns

Index(['Longitude', 'NbStations', 'EventID', 'Magnitude', 'MagType'], dtype='object')

In [ ]:
#Subtract 1,25,25,10,4 from columns in order. (Remember it can be done in one line of code)
#There is a non-numeric column in data, either it shold beexcluded or be converted to numeric data type.
#Let's first exclude it and then try also to convert it to numeric column.

df_new = df_new.drop('MagType', axis=1) - np.array([1,25,10,4])



In [ ]:
df_new.select_dtypes(include=None, exclude=object,) - np.array([1,25,10,4])

Longitude  NbStations       EventID  Magnitude
0     -1.0000       -49.0 -1.900000e+01       -7.0
1    149.4580        35.0  1.970011e+09       -1.8
2    176.5680         9.0  1.970011e+09       -1.9
3    124.7370        41.0  1.970011e+09       -1.9
4   -154.6600       -50.0           NaN       -2.0
5   -179.3490       125.0  1.970012e+09       -1.5
6    140.9660       149.0  1.970012e+09       -1.6
7   -106.2980        90.0  1.970012e+09       -1.4
8    164.3700        41.0  1.970013e+09       -1.6
9   -101.4840        50.0  1.970020e+09       -1.5
10   120.1170        44.0  1.970021e+09       -1.4
11    98.7750         7.0  1.970021e+09       -1.9
12   101.0310        44.0  1.970022e+09       -2.0
13  -181.5898       -50.0           NaN       -2.0
14  -177.0400       -50.0           NaN       -1.9
15   141.7070        32.0  1.970030e+09       -1.8
16   166.6030        11.0  1.970031e+09       -1.5
17   146.8700        15.0  1.970031e+09       -2.0
18  -155.9700       -50.0           NaN       -1.5
19   -71.4990        68.0  1.970032e+09       -2.0

In [ ]:
df_new

Longitude  NbStations       EventID  Magnitude
0      0.0000       -24.0 -9.000000e+00       -3.0
1    150.4580        60.0  1.970011e+09        2.2
2    177.5680        34.0  1.970011e+09        2.1
3    125.7370        66.0  1.970011e+09        2.1
4   -153.6600       -25.0           NaN        2.0
5   -178.3490       150.0  1.970012e+09        2.5
6    141.9660       174.0  1.970012e+09        2.4
7   -105.2980       115.0  1.970012e+09        2.6
8    165.3700        66.0  1.970013e+09        2.4
9   -100.4840        75.0  1.970020e+09        2.5
10   121.1170        69.0  1.970021e+09        2.6
11    99.7750        32.0  1.970021e+09        2.1
12   102.0310        69.0  1.970022e+09        2.0
13  -180.5898       -25.0           NaN        2.0
14  -176.0400       -25.0           NaN        2.1
15   142.7070        57.0  1.970030e+09        2.2
16   167.6030        36.0  1.970031e+09        2.5
17   147.8700        40.0  1.970031e+09        2.0
18  -154.9700       -25.0           NaN        2.5
19   -70.4990        93.0  1.970032e+09        2.0

In [ ]:
#Convert caterical column to numeric
df_new.MagType.unique()

AttributeError: ignored